---

- hosts: all
  sudo: true
  pre_tasks:
      # cache for 1 week
    - name: apt-get update
      apt: update_cache=yes cache_valid_time=604800

    - name: ensure required packages are installed for base config
      apt: name={{ item }} state=latest update_cache=yes cache_valid_time=604800
      with_items:
        - make
        - gcc
        - git
        - unzip
        - mongodb
        - maven
        - build-essential
        - libssl-dev
        - libffi-dev
        - python-dev
        - python-pip
        - python-dev
        - nginx
    - name: sync time
      shell: ntpdate pool.ntp.org

  roles:
    - glassfish4
    - crol-webapp
    - parser-address
